language: go

go:
  - "1.14"  

# Specify which branches to build using a safelist
# 分支白名单限制: 只有hugo分支的提交才会触发构建
branches:
  only:
    - sources 

# install:
# # 安装最新的hugo
#   - go get github.com/spf13/hugo 
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
# 运行hugo命令
  - hugo -e production

deploy:
  provider: pages 
  skip_cleanup: true 
  local_dir: public 
  target_branch: master
  token: $GITHUB_TOKEN 
  keep_history: true 
  on:
    branch: sources 
